FROM ubuntu:22.04

WORKDIR /app/backend

COPY requirements.txt .

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=EUROPE/Portugal

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    TZ=EUROPE/Portugal \ 
    apt-get -y install \
    build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev wget software-properties-common curl

RUN apt-get update && add-apt-repository ppa:deadsnakes/ppa && \
	apt update && \
	apt install -y python3.11 python3.11-dev python3.11-distutils && \
    apt install -y default-jdk

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
	python3.11 get-pip.py && \
	rm get-pip.py

RUN cd /usr/bin && \
    ln -s /usr/bin/python3.11 python && \
    cd -

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]